name: server-conda-env
channels:
- ioos
dependencies:
- openssl=1.0.2
- pip=19.3.1
- python=3.6
- setuptools=41.6.0
- sqlite=3.20.1
- wheel=0.29.0
- sphinx<1.7
- pip:
    - protobuf==3.3.0
    - candig-common
    - candig-schemas
    - sphinx-argparse
    - sphinx==1.6.7
    - pysam==0.9.1.4
    - RDFLib==4.2.2
    - peewee==3.13.1
    - pronto==1.1.2
    - readline==6.2.2
